'use client'

import { Alert } from "@/lib/stores/alerts"
import StreamingSummaryText from "@/components/dashboard/streaming-summary-text"
import { formatCoordinates } from "@/lib/location"
import { Badge } from "@/components/ui/badge"
import { MapPin, Clock } from "lucide-react"
import { cn } from "@/lib/utils"
import { useTick } from "@/hooks/use-tick"

const priorityConfig = {
  critical: { bar: "bg-red-500",    bg: "bg-red-500/[0.04]",    badge: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-900" },
  high:     { bar: "bg-orange-500", bg: "bg-orange-500/[0.04]", badge: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-900" },
  medium:   { bar: "bg-yellow-500", bg: "bg-yellow-500/[0.04]", badge: "bg-yellow-500/10 text-yellow-700 border-yellow-200 dark:border-yellow-900" },
}

const statusConfig = {
  active:   { dot: "bg-foreground", label: "Active" },
  resolved: { dot: "bg-muted-foreground/50",      label: "Resolved" },
}

function timeAgo(iso: string) {
  const diff = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (diff < 60)   return `${diff}s ago`
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
  return `${Math.floor(diff / 3600)}h ago`
}

export default function AlertCard({ alert, selected, onClick }: { alert: Alert; selected?: boolean; onClick?: () => void }) {
  useTick()
  const priority = priorityConfig[alert.priority]
  const status = statusConfig[alert.status]

  /* AI Citation: partly generated by Claude, but mostly modified and written by us. */
  return (
    <div
      onClick={onClick}
      className={cn(
        "flex border-b cursor-pointer transition-colors hover:bg-muted/50",
        priority.bg,
        selected && "bg-muted/80 hover:bg-muted/80"
      )}
    >
      <div className={cn("w-0.5 shrink-0", priority.bar)} />

      <div className="flex flex-col gap-2 px-5 py-3 min-w-0 w-full">
        <div className="flex items-center justify-between gap-2">
          <Badge variant="outline" className={cn("capitalize text-[10px] h-4 px-1.5", priority.badge)}>
            {alert.priority}
          </Badge>
          <div className="flex items-center gap-1 text-xs text-muted-foreground/50 tabular-nums" suppressHydrationWarning>
            <Clock className="size-3" />
            {timeAgo(alert.createdAt)}
          </div>
        </div>

        <p className="text-sm font-medium leading-snug line-clamp-2">
          <StreamingSummaryText text={alert.title} />
        </p>

        <p className="text-xs leading-relaxed text-muted-foreground line-clamp-2">
          {alert.subtitle}
        </p>

        <div className="flex items-center gap-1 text-xs text-muted-foreground min-w-0">
          <MapPin className="size-3 shrink-0" />
          <span className="truncate">{formatCoordinates(alert.location)}</span>
        </div>

        <div className="flex items-center justify-end gap-3">
          <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <span className={cn("size-1.5 rounded-full", status.dot)} />
            {status.label}
          </span>
        </div>

      </div>
    </div>
  )
}
