'use client'

import { Alert } from "@/lib/stores/alerts"
import { Badge } from "@/components/ui/badge"
import { MapPin, Mic, MicOff, Shield, Home, Heart, AlertTriangle, Clock } from "lucide-react"
import { cn } from "@/lib/utils"

const priorityConfig = {
  critical: { bar: "bg-red-500",    bg: "bg-red-500/[0.04]",    badge: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-900" },
  high:     { bar: "bg-orange-500", bg: "bg-orange-500/[0.04]", badge: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-900" },
  medium:   { bar: "bg-yellow-500", bg: "bg-yellow-500/[0.04]", badge: "bg-yellow-500/10 text-yellow-700 border-yellow-200 dark:border-yellow-900" },
}

const typeConfig = {
  "school-threat":     { label: "School Threat",     Icon: Shield },
  "domestic-violence": { label: "Domestic Violence", Icon: Home },
  "medical":           { label: "Medical",            Icon: Heart },
  "home-invasion":     { label: "Home Invasion",      Icon: AlertTriangle },
}

const statusConfig = {
  active:      { dot: "bg-red-500 animate-pulse", label: "Active" },
  stabilizing: { dot: "bg-yellow-500",            label: "Stabilizing" },
  resolved:    { dot: "bg-green-500",             label: "Resolved" },
}

function timeAgo(iso: string) {
  const diff = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (diff < 60)   return `${diff}s ago`
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
  return `${Math.floor(diff / 3600)}h ago`
}

export default function AlertCard({ 
  alert, 
  isSelected,
  onClick 
}: { 
  alert: Alert
  isSelected?: boolean
  onClick?: () => void
}) {
  const priority = priorityConfig[alert.priority]
  const type = typeConfig[alert.type]
  const status = statusConfig[alert.status]
  const { Icon } = type

  /* AI Citation: partly generated by Claude, but mostly modified and written by us. */
  return (
    <div 
      onClick={onClick}
      className={cn(
        "flex border-b cursor-pointer transition-colors hover:bg-muted/50",
        priority.bg,
        isSelected && "bg-accent/50 hover:bg-accent/50 ring-1 ring-inset ring-accent-foreground/20"
      )}
    >
      <div className={cn("w-0.5 shrink-0", priority.bar)} />

      <div className="flex flex-col gap-2 px-5 py-3 min-w-0 w-full">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Icon className="size-3" />
            <span>{type.label}</span>
          </div>
          <div className="flex items-center gap-1 text-xs text-muted-foreground/50 tabular-nums" suppressHydrationWarning>
            <Clock className="size-3" />
            {timeAgo(alert.createdAt)}
          </div>
        </div>

        <p className="text-sm font-medium leading-snug line-clamp-2">{alert.summary}</p>

        <div className="flex items-center gap-1 text-xs text-muted-foreground min-w-0">
          <MapPin className="size-3 shrink-0" />
          <span className="truncate">{alert.location}</span>
        </div>

        <div className="flex items-center justify-between gap-2">
          <Badge variant="outline" className={cn("capitalize text-[10px] h-4 px-1.5", priority.badge)}>
            {alert.priority}
          </Badge>
          <div className="flex items-center gap-3">
            {alert.safeToSpeak ? (
              <span className="flex items-center gap-1 text-xs text-green-600">
                <Mic className="size-3" /> Safe to speak
              </span>
            ) : (
              <span className="flex items-center gap-1 text-xs text-muted-foreground/50">
                <MicOff className="size-3" /> Silent
              </span>
            )}
            <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <span className={cn("size-1.5 rounded-full", status.dot)} />
              {status.label}
            </span>
          </div>
        </div>

      </div>
    </div>
  )
}
