/*
 * Citation: This component was (mostly) generated by Claude,
 * but the guidance/instructions were provided by us.
 */

import { create } from "zustand"
import type { LocationObjectCoords } from "@/lib/location"

export type AlertPriority = "critical" | "high" | "medium"
export type AlertStatus = "active" | "resolved"

export type TranscriptLine = {
  id?: string
  text: string
  at: string
}

export type AlertQuestion = {
  id: string
  text: string
  sentAt: string
  answeredAt?: string
  answer?: "yes" | "no"
}

export type MedicalInfo = {
  age?: number
  conditions?: string
}

export type Alert = {
  id: string
  meetingId?: string
  title: string
  subtitle: string
  streamTitle: string
  streamSummary: string
  priority: AlertPriority
  location: LocationObjectCoords | null
  status: AlertStatus
  createdAt: string
  updatedAt?: string
  transcript: TranscriptLine[]
  questions: AlertQuestion[]
  callersCount: number
  medicalInfo?: MedicalInfo
}

type AlertsState = {
  alerts: Alert[]
  addAlert: (newAlert: {
    title: string
    subtitle: string
    streamTitle: string
    streamSummary: string
    priority: AlertPriority
    location: LocationObjectCoords | null
    callersCount?: number
  }) => void
  advanceAlertStatus: (id: string) => void
}

export const useAlertsStore = create<AlertsState>()((set) => ({
  alerts: [],
  addAlert: (newAlert) =>
    set((state) => ({
      alerts: [
        {
          id: crypto.randomUUID(),
          ...newAlert,
          status: "active",
          createdAt: new Date().toISOString(),
          transcript: [],
          questions: [],
          callersCount: 1,
        },
        ...state.alerts,
      ],
    })),
  advanceAlertStatus: (id) =>
    set((state) => ({
      alerts: state.alerts.map((alert) =>
        alert.id === id
          ? {
              ...alert,
              updatedAt: new Date().toISOString(),
              status:
                alert.status === "active"
                  ? "resolved"
                  : "active",
            }
          : alert
      ),
    })),
}))

// Backward-compatible aliases while the codebase transitions from "incidents" to "alerts".
export type IncidentPriority = AlertPriority
export type IncidentStatus = AlertStatus
export type Incident = Alert
export const useIncidentsStore = useAlertsStore
