/*
 * Citation: This component was fully generated by Claude,
 * but the initial design was done by us.
 */
export default function OneLogo({
  color = "#0c0c0c",
  size = 1,
}: {
  color?: string;
  size?: number;
}) {
  const w = 280 * size;
  const h = 72 * size;

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 280 72"
      width={w}
      height={h}
      aria-label="One"
      role="img"
    >
      <circle
        cx="21"
        cy="34"
        r="18"
        fill="none"
        stroke={color}
        strokeWidth="5.75"
      />
      <rect
        x="14.5"
        y="27.5"
        width="13"
        height="13"
        rx="3.5"
        fill="#e8000d"
      />
      <text
        x="42"
        y="52"
        fontFamily="Inter, sans-serif"
        fontSize="52"
        fontWeight="500"
        fill={color}
        letterSpacing="-1"
      >
        ne
      </text>
    </svg>
  );
}