/*

 * Citation: This file was (mostly) generated by Claude,
 * but the guidance/instructions were provided by us.
 */

export type LocationObjectCoords = {
  latitude: number
  longitude: number
  altitude: number | null
  accuracy: number | null
  altitudeAccuracy: number | null
  heading: number | null
  speed: number | null
  address: string | null
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value)
}

function toOptionalNumber(value: unknown): number | null {
  return isFiniteNumber(value) ? value : null
}

export async function normalizeLocation(location: unknown): Promise<LocationObjectCoords | null> {
  if (!location || typeof location !== "object") return null

  const record = location as Record<string, unknown>
  const candidate =
    "coords" in record && record.coords && typeof record.coords === "object"
      ? (record.coords as Record<string, unknown>)
      : record

  if (!isFiniteNumber(candidate.latitude) || !isFiniteNumber(candidate.longitude)) {
    return null
  }

  return {
    latitude: candidate.latitude,
    longitude: candidate.longitude,
    altitude: toOptionalNumber(candidate.altitude),
    accuracy: toOptionalNumber(candidate.accuracy),
    altitudeAccuracy: toOptionalNumber(candidate.altitudeAccuracy),
    heading: toOptionalNumber(candidate.heading),
    speed: toOptionalNumber(candidate.speed),
    address: (await getAddressFromGeo(candidate.latitude, candidate.longitude) as unknown as string) ?? null,
  }
}

async function getAddressFromGeo(latitude: number, longitude: number){
  try {
    const response = await fetch(
      `https://nominatim.openstreetmap.org/reverse?format=json&lat=${latitude}&lon=${longitude}&zoom=18&addressdetails=1`,
      {
        headers: {
          Accept: "application/json",
          "User-Agent": "one/1.0",
        },
      }
    )

    const text = await response.text()

    if (!response.ok) {
      return null
    }

    try {
      const data = JSON.parse(text) as { display_name?: unknown }
      return typeof data.display_name === "string" ? data.display_name : null
    } catch {
      return null
    }
  } catch {
    return null
  }
}

export function formatCoordinates(location: LocationObjectCoords | null): string {
  if (!location) return "Unknown location"
  if (location.address) return location.address
  return `${location.latitude.toFixed(6)}, ${location.longitude.toFixed(6)}`
}

export function toLngLat(location: LocationObjectCoords | null): [number, number] | null {
  if (!location) return null
  return [location.longitude, location.latitude]
}

export function toLatLng(location: LocationObjectCoords | null): { lat: number; lng: number } | null {
  if (!location) return null
  return { lat: location.latitude, lng: location.longitude }
}
